application: led-o-matic
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: assets/index.html
  upload: assets/index.html
  
-  url: /a
   static_dir: assets
  

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /apple-touch-icon\.png
  static_files: assets/apple-touch-icon.png
  upload: assets/apple-touch-icon.png

- url: /robots\.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /admin/shell.*
  script: handlers/shell/shell.py
  login: admin

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*\.markdown)|
 (license\.txt)|
 (setup.py)
 )$